services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: water_delivery
    ports:
      - "5436:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
